CLASSPATH=.:src/net/veroy/analysis:lib/iris-0.60.jar:lib/iris-parser-0.60.jar:lib/iris-app-0.60.jar

all:
	@echo "Building Datalog Project. Please hold."
	@javac -cp ${CLASSPATH} src/net/veroy/analysis/*.java
	@echo "Compilation complete :)"